#!/usr/bin/env php
<?php

// Use all the memory
ini_set('memory_limit', '-1');
gc_enable();
error_reporting(1);
error_reporting(E_ALL);
define('DISCORDPHP_STARTTIME', microtime(true));
define('BASEDIR', __DIR__);
define('SOVEREIGN_CONFIG_FILE', BASEDIR . '/config/config.php');

// Load the autoloader
require_once(BASEDIR . '/vendor/autoload.php');

// Init the container object
$container = getContainer();

// Load the bot into the service container
$container->share('app', \Sovereign\Sovereign::class)->withArgument($container);

try {
    // Init the bot
    $container->get('log')->addInfo('Sovereign is starting up..');
    $bot = $container->get('app');

    // Register the default plugins and services, and boot them.
    $container->addServiceProvider(\Sovereign\Service\SystemPluginServiceProvider::class);
} catch (\Exception $e) {
    $container->get('log')->addError('An error occurred: ' . $e->getMessage());
    die();
}

// Launch the bot
$bot->run();
